
CREATE TABLE `contact_record` (
  `CONTACT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTACT_TIME` timestamp NULL DEFAULT NULL,
  `CONTACT_CONTENT` tinytext,
  `CONTACT_PERSON` varchar(255) DEFAULT NULL,
  `CONTACT_PHONE` varchar(255) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`CONTACT_ID`),
  UNIQUE KEY `CONTACT_ID_UNIQUE` (`CONTACT_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=43 DEFAULT CHARSET=utf8 COMMENT='客户联系记录';
 
CREATE TABLE `contract` (
  `CONTRACT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SIGN_PERSON_A` varchar(45) DEFAULT NULL,
  `SIGN_DATE` date DEFAULT NULL,
  `ADVANCED_AMOUNT` decimal(36,2) DEFAULT NULL,
  `ADVANCED_AMOUNT_DATE` date DEFAULT NULL,
  `BALANCED_AMOUNT` decimal(36,2) DEFAULT NULL,
  `BALANCED_AMOUNT_DATE` date DEFAULT NULL,
  `ADVANCED_AMOUNT_STATUS` varchar(45) DEFAULT NULL,
  `BALANCED_AMOUNT_STATUS` varchar(45) DEFAULT NULL,
  `PROJECT_ID` varchar(255) DEFAULT NULL,
  `SIGN_PERSON_B` varchar(45) DEFAULT NULL,
  `CONTRACT_PAPER_ID` varchar(45) DEFAULT NULL,
  `CONTRACT_TYPE` varchar(45) DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  `TOTAL_AMOUNT` int(11) DEFAULT NULL,
  `AD_CONFIMER` varchar(45) DEFAULT NULL,
  `BA_CONFIMER` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`CONTRACT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8;
 
CREATE TABLE `customers` (
  `CUSTOMER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_NAME` varchar(128) NOT NULL,
  `SEX` char(2) NOT NULL,
  `AGE` int(5) DEFAULT NULL,
  `PHONE` varchar(45) DEFAULT NULL,
  `CELLPHONE` varchar(45) DEFAULT NULL,
  `WORK_UNIT` varchar(45) DEFAULT NULL,
  `DEPARTMENT` varchar(45) DEFAULT NULL,
  `POSITION` varchar(45) DEFAULT NULL,
  `EMAIL` varchar(45) DEFAULT NULL,
  `ADRESS` varchar(45) DEFAULT NULL,
  `RESEARCH_DIRECTION` varchar(45) DEFAULT NULL,
  `RESPONSIBLE_AREA` varchar(45) DEFAULT NULL,
  `CUSTOMER_LEVEL` int(11) DEFAULT '1',
  `PRINCIPAL_ID` int(11) DEFAULT NULL,
  `PROJECT_ID` varchar(255) DEFAULT NULL,
  `RELATIONSHIP` varchar(45) DEFAULT NULL,
  `PRINCIPAL_NUM` int(11) DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8;
 
CREATE TABLE `document` (
  `FileId` int(11) NOT NULL AUTO_INCREMENT,
  `FileName` varchar(255) NOT NULL,
  `FilePath` varchar(255) NOT NULL,
  `FileOwnerId` int(11) NOT NULL COMMENT '用户id',
  `FileOwner` varchar(255) NOT NULL,
  `FileType` smallint(4) NOT NULL COMMENT '文件类型 0:文件 1:文件夹',
  `ParentId` int(11) NOT NULL DEFAULT '0' COMMENT '父级文件夹id,为0表示为root节点',
  `AddTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`FileId`),
  KEY `IX_parent` (`ParentId`),
  KEY `IX_addTime` (`AddTime`),
  KEY `UX_FileName` (`FileName`,`FileOwnerId`)
) ENGINE=MyISAM AUTO_INCREMENT=10061 DEFAULT CHARSET=utf8 COMMENT='项目文档';
 
CREATE TABLE `employee` (
  `EMPLOYEE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_NAME` varchar(127) NOT NULL,
  `FK_EMPLOYEE_ROLE_ID` int(11) NOT NULL,
  `FK_PRIVILEGE_ID` int(11) DEFAULT NULL,
  `PASSWORD` varchar(127) DEFAULT NULL,
  `EMAIL` varchar(127) DEFAULT NULL COMMENT '邮箱',
  PRIMARY KEY (`EMPLOYEE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8;
 
CREATE TABLE `employee_role` (
  `EMPLOYEE_ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ROLE` char(2) NOT NULL,
  `DESCRIPTION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEE_ROLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
 
CREATE TABLE `literature` (
  `LITERATURE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) DEFAULT NULL,
  `AUTHOR` varchar(255) NOT NULL,
  `PUBLICATION_YEAR` date DEFAULT NULL,
  `LOCATIONS` varchar(255) DEFAULT NULL,
  `ABSTRACT` varchar(255) DEFAULT NULL,
  `DISK_URL` varchar(255) DEFAULT NULL COMMENT '文件地址',
  `DIRECTION` varchar(255) DEFAULT NULL,
  `BACKGROUND` varchar(255) DEFAULT NULL,
  `TECHNOLOGYWAY` varchar(255) DEFAULT NULL,
  `TECHNOLOGY_PLATFORM` varchar(63) DEFAULT NULL,
  `CONCLUSION` varchar(255) DEFAULT NULL,
  `LIGHT_SPOT` varchar(255) DEFAULT NULL,
  `RESEARCHENLIGHTENMENT` varchar(255) DEFAULT NULL,
  `PRODUCTENLIGHTENMENT` varchar(255) DEFAULT NULL,
  `PLATFORMENLIGHTENMENT` varchar(255) DEFAULT NULL,
  `COMMENTS` varchar(255) DEFAULT NULL,
  `PROBLEM` varchar(255) DEFAULT NULL,
  `ATTACHEDHOTSPOT` varchar(45) DEFAULT NULL,
  `addTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`LITERATURE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8 COMMENT='文献数据库';
 
CREATE TABLE `message` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SenderId` int(11) NOT NULL COMMENT '发送者(0为admin)',
  `ReceiverId` int(11) NOT NULL COMMENT '接收者id',
  `SendTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '消息产生时间',
  `Status` smallint(6) DEFAULT '0' COMMENT '0 未读,1已读,2删除',
  `MsgTextId` int(11) DEFAULT NULL COMMENT '消息内容对应id',
  PRIMARY KEY (`ID`),
  KEY `IX_receive` (`ReceiverId`),
  KEY `IX_status` (`Status`),
  KEY `IX_sendTime` (`SendTime`),
  KEY `IX_msgtextId` (`MsgTextId`)
) ENGINE=MyISAM AUTO_INCREMENT=134 DEFAULT CHARSET=utf8;
 
CREATE TABLE `message_text` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `MessageText` varchar(255) NOT NULL COMMENT '消息内容',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=114 DEFAULT CHARSET=utf8;
 
CREATE TABLE `out_source` (
  `OUT_SOURCE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `OUT_SOURCE_UNIT` varchar(125) DEFAULT NULL,
  `ADRESS` text,
  `SEND_SAMPLE_DATE` date DEFAULT NULL,
  `SEND_SAMPLE_COUNT` int(11) DEFAULT NULL,
  `IS_EXPERIMENT_RESULT_RECIVED` int(11) DEFAULT NULL,
  `OUT_SOURCE_STATUS` varchar(45) DEFAULT NULL,
  `FK_PROJECT_ID` varchar(255) DEFAULT NULL,
  `OUT_SOURCE_TYPE` varchar(45) DEFAULT NULL,
  `CONTACT_PERSON` varchar(45) DEFAULT NULL,
  `CONTACT_PHONE` varchar(45) DEFAULT NULL,
  `CONTRACT_AMOUNT` decimal(36,2) DEFAULT NULL,
  `CONTRACT_INFO` text,
  `DATA_SOURCE` varchar(255) DEFAULT NULL,
  `DATA_NUM` varchar(255) DEFAULT NULL,
  `ANALYZE_INFO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`OUT_SOURCE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8;
 
CREATE TABLE `privilege` (
  `PRIVILEGE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLE` varchar(45) NOT NULL,
  `DESCRIPTION` varchar(45) DEFAULT NULL,
  `Privileges` varchar(255) NOT NULL COMMENT '权限',
  PRIMARY KEY (`PRIVILEGE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
 
CREATE TABLE `project` (
  `PROJECT_ID` varchar(255) NOT NULL,
  `NEED_PRINCPAL_ASSIST` char(2) NOT NULL DEFAULT 'N' COMMENT '是否需要主管协助',
  `PRIORITY` int(11) DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  `PROJECT_CONTENT` varchar(255) DEFAULT NULL,
  `POTENTIAL_EXPENDITURE` varchar(50) DEFAULT NULL COMMENT '项目潜在经费',
  `SAMPLE_COUNT` int(11) DEFAULT NULL COMMENT '样本数量',
  `RESEARCH_DIRECTION` varchar(90) DEFAULT NULL COMMENT '研究方向',
  `TECHNOLOGY_PLATFORM_DEMAND` varchar(255) DEFAULT NULL COMMENT '技术平台要求',
  `HAS_CORPORATED_INTENTION` char(2) DEFAULT NULL COMMENT '是否有意10X1000合作',
  `NEED_PROJECT_PLAN` char(2) DEFAULT NULL COMMENT '课题方案是否需要',
  `NEED_SCI` char(2) DEFAULT NULL COMMENT '需要发SCI文章',
  `PROJECT_NOTE` varchar(255) DEFAULT NULL COMMENT '项目备注',
  `TYPE_TRANSFER_INFO` int(11) DEFAULT NULL,
  `PROJECT_NAME` varchar(45) DEFAULT NULL,
  `PROJECT_TYPE` varchar(45) DEFAULT NULL COMMENT '项目类型',
  `PROJECT_PERCENTAGE` smallint(6) NOT NULL DEFAULT '0',
  `ASSIGN_CONTENT` text,
  PRIMARY KEY (`PROJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
CREATE TABLE `project_employee` (
  `PROJECT_ID` varchar(255) NOT NULL,
  `EMPLOYEE_ID` int(11) NOT NULL,
  PRIMARY KEY (`PROJECT_ID`,`EMPLOYEE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
CREATE TABLE `project_progress` (
  `PROJECT_PROGRESS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLOYEE_ID` int(11) NOT NULL,
  `EMPLOYEE_NAME` varchar(64) NOT NULL,
  `PROGRESS_CONTENT` varchar(255) DEFAULT NULL,
  `PROGRESS_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `PROJECT_ID` varchar(255) NOT NULL,
  `PERCENTAGE` int(11) NOT NULL COMMENT '进度百分比',
  PRIMARY KEY (`PROJECT_PROGRESS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=160 DEFAULT CHARSET=utf8;
 
CREATE TABLE `sample` (
  `SAMPLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` varchar(255) DEFAULT NULL,
  `SAMPLE_PRINCRIPAL` varchar(45) DEFAULT NULL,
  `RECIVED_DATE` date DEFAULT NULL,
  `DISK_LOCATION` varchar(255) DEFAULT NULL,
  `SOURCE_UNIT` varchar(45) DEFAULT NULL,
  `SAMPLE_AMOUNT` int(11) DEFAULT NULL,
  `REPORT_DATE` date DEFAULT NULL,
  `DELIVERY_NUM` varchar(45) DEFAULT NULL,
  `SAMPLE_TYPE` varchar(45) DEFAULT NULL,
  `IS_DELIVERY` char(2) DEFAULT NULL,
  `PROJECT_PRINCRIPAL` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SAMPLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8;
