/*
-- Query: SELECT * FROM test.customers
LIMIT 0, 1000

-- Date: 2014-11-09 11:55
*/
INSERT INTO `customers` (`CUSTOMER_ID`,`CUSTOMER_NAME`,`SEX`,`AGE`,`PHONE`,`CELLPHONE`,`WORK_UNIT`,`DEPARTMENT`,`POSITION`,`EMAIL`,`ADRESS`,`RESEARCH_DIRECTION`,`RESPONSIBLE_AREA`,`CUSTOMER_LEVEL`,`PRINCIPAL_ID`,`PROJECT_ID`,`RELATIONSHIP`,`PRINCIPAL_NUM`) VALUES (1,'Robin','男',28,'110','15000000000','SAP','保洁部','部长','123123122@wqe.com','金科路','脚气',NULL,1,NULL,1,NULL,1);
INSERT INTO `customers` (`CUSTOMER_ID`,`CUSTOMER_NAME`,`SEX`,`AGE`,`PHONE`,`CELLPHONE`,`WORK_UNIT`,`DEPARTMENT`,`POSITION`,`EMAIL`,`ADRESS`,`RESEARCH_DIRECTION`,`RESPONSIBLE_AREA`,`CUSTOMER_LEVEL`,`PRINCIPAL_ID`,`PROJECT_ID`,`RELATIONSHIP`,`PRINCIPAL_NUM`) VALUES (2,'Semmon','男',27,'119','15111111111','INFOSYS','保安部','副部长','222222@22.com','大唐镇','保健','大保健',1,1,1,'同事',2);
INSERT INTO `customers` (`CUSTOMER_ID`,`CUSTOMER_NAME`,`SEX`,`AGE`,`PHONE`,`CELLPHONE`,`WORK_UNIT`,`DEPARTMENT`,`POSITION`,`EMAIL`,`ADRESS`,`RESEARCH_DIRECTION`,`RESPONSIBLE_AREA`,`CUSTOMER_LEVEL`,`PRINCIPAL_ID`,`PROJECT_ID`,`RELATIONSHIP`,`PRINCIPAL_NUM`) VALUES (3,'Tony','男',26,'120','15222222222222','携程','门卫部','第二门卫','32365@aa.com','湖北','看门','偏门',1,1,1,'上下级',3);
