/*
-- Query: SELECT * FROM test.employee
LIMIT 0, 1000

-- Date: 2014-11-05 23:33
*/
INSERT INTO `employee` (`EMPLOYEE_ID`,`EMPLOYEE_NAME`,`FK_EMPLOYEE_ROLE_ID`,`FK_PRIVILEGE_ID`,`PASSWORD`) VALUES (1,'ivan',2,2,'123456');
INSERT INTO `employee` (`EMPLOYEE_ID`,`EMPLOYEE_NAME`,`FK_EMPLOYEE_ROLE_ID`,`FK_PRIVILEGE_ID`,`PASSWORD`) VALUES (2,'terry',2,2,'123456');
INSERT INTO `employee` (`EMPLOYEE_ID`,`EMPLOYEE_NAME`,`FK_EMPLOYEE_ROLE_ID`,`FK_PRIVILEGE_ID`,`PASSWORD`) VALUES (3,'james',2,1,'123456');
