/*
-- Query: SELECT * FROM test.project
LIMIT 0, 1000

-- Date: 2014-11-05 21:49
*/
INSERT INTO `project` (`PROJECT_ID`,`NEED_PRINCPAL_ASSIST`,`PRIORITY`,`START_DATE`,`END_DATE`,`PROJECT_CONTENT`,`POTENTIAL_EXPENDITURE`,`SAMPLE_COUNT`,`RESEARCH_DIRECTION`,`TECHNOLOGY_PLATFORM_DEMAND`,`HAS_CORPORATED_INTENTION`,`NEED_PROJECT_PLAN`,`NEED_SCI`,`PROJECT_NOTE`,`TYPE_TRANSFER_INFO`,`PROJECT_NAME`) VALUES (1,'N',1,'2009-09-09','2009-09-09',NULL,'null',5,'感冒','11',NULL,NULL,'Y',NULL,NULL,NULL);
INSERT INTO `project` (`PROJECT_ID`,`NEED_PRINCPAL_ASSIST`,`PRIORITY`,`START_DATE`,`END_DATE`,`PROJECT_CONTENT`,`POTENTIAL_EXPENDITURE`,`SAMPLE_COUNT`,`RESEARCH_DIRECTION`,`TECHNOLOGY_PLATFORM_DEMAND`,`HAS_CORPORATED_INTENTION`,`NEED_PROJECT_PLAN`,`NEED_SCI`,`PROJECT_NOTE`,`TYPE_TRANSFER_INFO`,`PROJECT_NAME`) VALUES (2,'N',3,'2009-09-09','2009-09-09',?,'null',5,'鼻炎','12',NULL,NULL,'Y',?,NULL,NULL);
INSERT INTO `project` (`PROJECT_ID`,`NEED_PRINCPAL_ASSIST`,`PRIORITY`,`START_DATE`,`END_DATE`,`PROJECT_CONTENT`,`POTENTIAL_EXPENDITURE`,`SAMPLE_COUNT`,`RESEARCH_DIRECTION`,`TECHNOLOGY_PLATFORM_DEMAND`,`HAS_CORPORATED_INTENTION`,`NEED_PROJECT_PLAN`,`NEED_SCI`,`PROJECT_NOTE`,`TYPE_TRANSFER_INFO`,`PROJECT_NAME`) VALUES (3,'Y',2,'2009-09-09','2009-09-09',NULL,NULL,1,'胃炎','3',NULL,NULL,'N',NULL,NULL,NULL);
INSERT INTO `project` (`PROJECT_ID`,`NEED_PRINCPAL_ASSIST`,`PRIORITY`,`START_DATE`,`END_DATE`,`PROJECT_CONTENT`,`POTENTIAL_EXPENDITURE`,`SAMPLE_COUNT`,`RESEARCH_DIRECTION`,`TECHNOLOGY_PLATFORM_DEMAND`,`HAS_CORPORATED_INTENTION`,`NEED_PROJECT_PLAN`,`NEED_SCI`,`PROJECT_NOTE`,`TYPE_TRANSFER_INFO`,`PROJECT_NAME`) VALUES (4,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
